-- One row per completed scan. The payload is the full Inventory as JSON; it is read whole, never queried by field.
CREATE TABLE inventory_snapshot (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    payload      CLOB NOT NULL
);

CREATE INDEX inventory_snapshot_collected_at ON inventory_snapshot (collected_at DESC);
