-- Append-only record of who did what. Also written to the Windows Event Log (source VmPatchAgent), which survives a
-- snapshot revert only if it is forwarded off the VM.
CREATE TABLE audit_event (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at     TIMESTAMP WITH TIME ZONE NOT NULL,
    actor  VARCHAR(200)  NOT NULL,
    action VARCHAR(40)   NOT NULL,
    job_id BIGINT,
    detail VARCHAR(4000)
);

CREATE INDEX audit_event_at ON audit_event (at DESC);

-- An approved set of fixes. items is the plan as the approver saw it, frozen at approval time.
CREATE TABLE remediation_job (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status                VARCHAR(24)  NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    approved_by           VARCHAR(200) NOT NULL,
    allow_reboot          BOOLEAN      NOT NULL,
    os_build_at_approval  VARCHAR(40)  NOT NULL,
    items                 CLOB         NOT NULL,
    snapshot_name         VARCHAR(80),
    snapshot_requested_at TIMESTAMP WITH TIME ZONE,
    snapshot_created_at   TIMESTAMP WITH TIME ZONE,
    snapshot_removed_at   TIMESTAMP WITH TIME ZONE,
    status_detail         VARCHAR(2000)
);
