package com.sandeeprathore.vmpatchagent.audit;

public enum AuditAction {

	SIGN_IN, SIGN_IN_FAILED, JOB_APPROVED, SNAPSHOT_CREATED, SNAPSHOT_FAILED, JOB_CANCELLED, SNAPSHOT_DELETED,
	SNAPSHOT_DELETE_FAILED, REVERT_DETECTED, JOB_FAILED

}
